name:                untyped
version:             0.2.0.0
license:             GPL-3
author:              "Luca De Paulis"
copyright:           "2020 Luca De Paulis"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lucadp19/TaPL-Haskell/tree/master/untyped#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- mtl
- transformers
- prettyprinter
- exceptions
- haskeline >= 0.8.1.1

library:
  source-dirs: src

tests:
  untyped-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    default-extensions:
    - OverloadedStrings
    dependencies:
    - untyped
