name:                arith
version:             0.1.0.0
github:              "lucadp19/arith"
license:             BSD3
author:              "Luca De Paulis"
maintainer:          "example@example.com"
copyright:           "2020 Luca De Paulis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lucadp19/TaPL-Haskell/tree/master/arith#readme>

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec
- transformers
- prettyprinter
- haskeline

library:
  source-dirs: src

executables:
  arith-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -XOverloadedStrings
    dependencies:
    - arith

tests:
  arith-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -XOverloadedStrings
    dependencies:
    - arith
